### ISSUE TITLE
Error installing plugins when DT is enabled.

### ISSUE THREAD

**Issue by spark108** [ticktackk/DeveloperToolsForXF2#1]
![image](https://user-images.githubusercontent.com/16227774/35805053-66ca28f4-0a8b-11e8-9dc2-6069f67e7688.png)

**Comment by ticktackk** [comment]
Which add-on were you trying to install?

**Comment by spark108** [comment]
When installing any add-on, after installing your.

**Comment by ticktackk** [comment]
I'm unable to reproduce this with both Resource Manager and Media Gallery. I would need to know steps to reproduce this issue.

Edit: I would need a screenshot of installed add-on(s) from that installation.

**Comment by spark108** [comment]
Apparently, errors originated from some old versions, for example, in version 1 it was wrong to assign MEDIUMTEXT to the default value of null. In later versions, for some reason, your fields from xf_addon disappeared. Now I added them all works.
