### ISSUE TITLE
Create addon button within adminCP

### ISSUE THREAD

**Issue by TylerAustin7** [ticktackk/DeveloperToolsForXF2#105]
Is any possible you can add create addon button in adminCP. I don’t wanted to used SSH Shell

**Comment by ticktackk** [comment]
Create add-on button already exists but there is a bug with it.

**Comment by TylerAustin7** [comment]
Are you going to fix the bug so I can able to create addon within adminCP

**Comment by ticktackk** [comment]
There was a release day on the same day: https://github.com/ticktackk/DeveloperToolsForXF2/releases/tag/1030670 I suggest you check the patch notes of it.
