### ISSUE TITLE
entity-class-properties should generate readonly property definitions for relationships and getters

### ISSUE THREAD

**Issue by Xon** [ticktackk/DeveloperToolsForXF2#122]
Similar to https://xenforo.com/community/threads/xf-dev-entity-class-properties-generates-phpdocs-which-indicate-readonly-properties-are-writeable.204571/

Readonly properties should be defined similar to this;
```
* COLUMNS
* @property string $name1_
* GETTERS
* @property string $name1
* @property-read string $name2
* RELATIONS
* @property-read string $name3
```

For relationships, an XF entity will reject updating a relationship property.
For getters, unless it overshadows an existing column, it will reject updating a getter property.

**Comment by ticktackk** [comment]
@Xon can you take a look at the commit I pushed and see if it fixes the issue you are reporting?

**Comment by Xon** [comment]
Looks good!
